[package]
name = "simple-rust-template"
description = "Very simple rust-github-project-template."
authors = ["neinteen"]
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
license-file = "LICENSE"

[[bin]]
name = "simple-rust-template"
path = "src/main.rs"

[dependencies]
